#! /usr/bin/env node

const { $ } = require('./helpers');
const { getRepoInfo } = require('./repo');

const { releaseBranch, prTitle, productionBranch, milestone } = getRepoInfo();

// publish branch
console.log($(`hub push --follow-tags --set-upstream origin ${releaseBranch}`));
// create pull request
console.log($(`hub pull-request --no-edit --message "${prTitle}" --base "${productionBranch}" --milestone "${milestone}"`));
