#! /usr/bin/env node

const { $$ } = require('./helpers');
const { getEnvironment } = require('./environment');
const { getRepoInfo } = require('./repo');

const { packageVersion } = getEnvironment();
const { releaseBranch } = getRepoInfo();

const bumpPlugin = `@jarrodldavis/changelog-version-bump=version:'${packageVersion}'`;

// create new release branch
$$(`hub checkout -b ${releaseBranch}`);
// update changelog with new version
$$(`remark CHANGELOG.md -o --use "${bumpPlugin}"`);
// add changelog to staging (npm will handle creating the commit)
$$('hub add CHANGELOG.md');
