#! /usr/bin/env node

const { $$ } = require('./helpers');
const { getEnvironment } = require('./environment');
const { getRepoInfo, ensureUnreleased } = require('./repo');

const { versionPrefix, packageVersion } = getEnvironment();
const { releaseBranch, defaultBranch } = getRepoInfo();

const bumpPlugin = `@jarrodldavis/changelog-version-bump=version:'${packageVersion}'`;

// ensure new version hasn't already been released
ensureUnreleased(`${versionPrefix}${packageVersion}`, defaultBranch);
// create new release branch
$$(`hub checkout -b ${releaseBranch}`);
// update changelog with new version
$$(`remark CHANGELOG.md -o --use "${bumpPlugin}"`);
// add changelog to staging (npm will handle creating the commit)
$$('hub add CHANGELOG.md');
