#! /usr/bin/env node

const { $$ } = require('./helpers');
const { getRepoInfo, ensureSynchronized, ensureNoOtherBumps } = require('./repo');

const { remote, defaultBranch, productionBranch } = getRepoInfo();

// checkout development branch
$$(`hub checkout ${defaultBranch}`);
// bring in any changes from upstream
$$(`hub sync`);
// ensure local and remote head branch are in sync (`hub sync` only warns)
ensureSynchronized();
// ensure no other version bumps are in progress (unmerged tags or release branches)
ensureNoOtherBumps(remote, defaultBranch, productionBranch);
// run test suite
$$(`npm test`);
